---
services:
  consul:
    image: hashicorp/consul:1.21
    hostname: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "${CONSUL_PORT:-8500}:8500/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"
